package com.ppg.iicsdoc.model.markdown;

import java.util.Map;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Model representing metadata for a markdown document.
 * 
 * @author Carlos Salguero
 * @version 1.0.0
 * @since 2025-10-23
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class DocumentMetadata {
    
    /** Source file information */
    private String sourceFile;

    /** Process name */
    private String processName;

    /** Process version information */
    private String processVersion;

    /** The process's author */
    private String author;

    /** Generated by */
    private String generatedBy;

    /** Custom metadata object */
    private Map<String, Object> customMetadata;
}
