/**
 * Provides services and utilities for generating Markdown documentation
 * from parsed IICS metadata and Mermaid diagrams.
 *
 * <p>This package includes components responsible for transforming structured
 * metadata into rich Markdown documents suitable for deployment and publication.
 * It supports templating, formatting, and metadata enrichment.
 *
 * <p>Key components:
 * <ul>
 *   <li>{@link com.ppg.iicsdoc.generator.MarkdownGeneratorService} – Core service for rendering Markdown using FreeMarker templates</li>
 *   <li>{@link com.ppg.iicsdoc.generator.MarkdownUtil} – Utility class for generating Markdown elements such as headers, links, tables, and code blocks</li>
 * </ul>
 *
 * <p>Documents generated by this package typically include:
 * <ul>
 *   <li>Process flow diagrams</li>
 *   <li>API endpoint diagrams</li>
 *   <li>Structured metadata extracted from IICS XML files</li>
 * </ul>
 *
 * <p>Designed for use within a Spring context, these components are integrated
 * into the documentation generation pipeline.
 *
 * @author Carlos Salguero
 * @version 1.0.0
 * @since 2025-10-23
 */
package com.ppg.iicsdoc.generator;